apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-fpm
  namespace: laravel-app
  labels:
    tier: backend
    layer: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      initContainers:
        - name: migrations
          image: my-registry/cli:latest
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
            - configMapRef:
                name: laravel
            - secretRef:
                name: laravel
      containers:
        - name: fpm
          image: my-registry/fpm_server:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel
            - secretRef:
                name: laravel
      imagePullSecrets:
        - name: docker-registry-creds